### PR TITLE
Paginate services

### PR DESCRIPTION
**Pull request by steve-gray**
@josmo 

If a service is not in the first page, this plugin was not checking .Next() and paginating - Rancher defaults to 100 items returned, maxing out at 1000.

In future I'll submit a seperate PR relating to pagination over environments (much less of a problem).

### CODE REVIEW

**Comment by steve-gray** [comment]
@josmo - Is there any chance of getting this released this week? If there's any questions or problems, let me know and I'll fix ASAP.

**Comment by josmo** [comment]
Thanks @steve-gray, I'll take a look in a couple hours and will merge asap

**Comment by josmo** [comment]
@steve-gray it should be published, let me know if you run into any issues.

**Comment by josmo** [comment]
@steve-gray actually looks like it breaks the plugin. I'm going to try to fix but may have to back this out. Looks like the break, breaks out of one loop but not the other and gets stuck infinitely.

**Comment by josmo** [comment]
ok I fixed the breaking out of the parent loop. when I get a change I'll look at making a it a bit more clear on what it's doing.

**Comment by steve-gray** [comment]
Cheers:  I'm not 100% happy with it either - A likely better fix is to use the filters to search for exact service names - but I'll be damned if I can find *any* docs on the API syntax for what it's expecting for passing the service names. I  was going to break out wireshark and see how the UI handles this.....

A far less urgent problem is reaching 100 environments which will have the same problem.

**Comment by josmo** [comment]
Yeah 100 environments is probably a little less used ;) I don't know if you know this but you can hit {rancherhost}/v2-beta/stacks and it will give you a good idea of what filters are available and what not :)  When I get a change I'll dig more but if you were going down that path I thought it might help

**Pull request merged**
