### PR TITLE
Add support for Drone 0.5

### PR DESCRIPTION
**Pull request by mccricardo**

### CODE REVIEW

**Comment by majest** [comment]
Hi. Perhaps not entirely compatible with what you guys are doing here but I've rewritten the plugin for my own needs and it's compatible with 0.5. https://github.com/majest/drone-rancher. Also if anyone is interested I have published a rancher-catalog for drone 0.5, available here: https://github.com/majest/rancher-catalog

**Comment by appleboy** [comment]
Any updates on this?

**Comment by roasten** [comment]
@majest Does this one include rancher support for CD?

**Comment by josmo** [comment]
I'm going to close this since master now is up to date on .5

**Pull request closed without merging**
