### PR TITLE
Wait for upgrade to complete before confirming.

### PR DESCRIPTION
**Pull request by johnrengelman**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
LGTM

**Comment by johnrengelman** [comment]
I cleaned this up a bit... I think the `retry` function might be useful to pull into drone/drone-go so other plugins can reuse it.

**Comment by studna** [comment]
I just looking for this feature, many thanks @johnrengelman ! Can you please merge it? ping @nlf

**Comment by nlf** [comment]
LGTM

**Comment by nlf** [comment]
@johnrengelman you'll need to merge master into your branch so we can merge this

**Comment by johnrengelman** [comment]
@nlf rebased.

**Pull request merged**
